[project]
name = "yt-video-summarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.8.5",
    "jupyter>=1.1.1",
    "pandas>=3.0.2",
    "scikit-learn>=1.8.0",
    "sentence-transformers>=5.4.1",
    "spacy>=3.8.14",
    "tqdm>=4.67.3",
    "youtube-transcript-api>=1.2.4",
]
